#!/home/vagrant/django/python_env/bin/python

from subprocess import call
import sys

message = "1"


if {{ stage }}  == 1:
    
    call([sys.executable,"-m","pip","install","django==2.1"])
    call([sys.executable,"/home/{{ user }}/{{ django}}/{{ env }}/bin/django-admin","startproject","{{ project }}","/home/{{ user }}/{{ django }}"])

    if message == "1":
        print()
        print("comment='stage 1 succesful'")
    else:
        print("comment='stage 1 succesfull. mysql status {}'".format(message))

else: 
     call([sys.executable,"/home/{{ user }}/{{ django }}/manage.py","collectstatic"])
     call([sys.executable, "/home/{{ user }}/{{ django }}/manage.py","makemigrations"])
     call([sys.executable, "/home/{{ user }}/{{ django }}/manage.py","migrate"])

     print()
     print("comment='stage 2 succesful'")



